overrides:
  undici: 6.28.0
  undici@<6.28.1: ^6.28.1
  undici@>=6.25.0 <6.28.1: ^6.28.1
  undici@>=6.7.0 <6.28.1: ^6.28.1

allowBuilds:
  esbuild: set this to true or false
  'esbuild@0.28.1': true

minimumReleaseAgeExclude:
  - undici@6.28.1
